### ISSUE TITLE
Plugin is broken in Pipes Cloud

### ISSUE THREAD

**Issue by badideasforsale** [turbot/steampipe-plugin-crtsh#26] opened 2024-03-20 16:47 UTC
**Describe the bug**
Plugin is broken; queries (including datatank harvesting) error with
```
Error: rpc error: code = Internal desc = crtsh: rpc error: code = Internal desc = hydrate function listCertificate failed with panic setting PGSYSCONFDIR not supported (SQLSTATE HV000)
```
**Steampipe version (`steampipe -v`)**
`Steampipe v0.22.0` locally, but this occurs in Pipes as well.

**Plugin version (`steampipe plugin list`)**
Unclear, this is running in Pipes

**To reproduce**
Query one of the tables provided by the plugin. For example:
```sql
select dns_names, not_after, not_before  from crtsh_certificate where query = 'turbot.com' AND not_after > now()
```

**Expected behavior**
The query returns results :)

**Additional context**

**Comment by e-gineer** [comment] 2024-03-21 11:13
The query above is working for me in Pipes at the moment.

I suspect that it was a problem with the crt.sh service at the time you tried it?

crt.sh is unique in that the entire service runs off a Postgres database - including the HTTP layer! So, if you are getting Postgres errors while using it then it can (unexpectedly) be a problem on the crt.sh server side rather than on the steampipe side.

Could you please try again?

**Comment by misraved** [comment] 2024-04-29 07:12
Hello @badideasforsale ,

Since we haven't received any further responses, and we are unable to reproduce the issue with the information provided, I will be closing it for now. If you encounter the same issue again or have any more details to share, please feel free to reopen this issue. Happy to help!

Thank you for reaching out, and we look forward to assisting you if you have additional questions👍.

**Closed by misraved** 2024-04-29 07:12 UTC
Labels: bug
